name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches:
      - main


jobs:
  docker_publish:
    runs-on: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build Image 
        run: docker-compose build

      - name: Push to GHCR
        run: docker-compose push