name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches:
      - main


jobs:
  docker_publish:
    runs-on: "ubuntu-22.04"
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image 
        run:  docker buildx bake --file docker-compose.yml --file docker-compose-cache.json

      - name: Push to GHCR
        run: docker-compose push

      - name: Pull
        run: docker pull ghcr.io/ohthatmagicfeelin/actions-playground:latest