name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches:
      - main


jobs:
  docker_publish:
    runs-on: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}


      - name: Build and Push to GHCR
        run: |

          docker-compose build
          docker-compose push
